<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Backup Code\**" />
    <Content Remove="Backup Code\**" />
    <EmbeddedResource Remove="Backup Code\**" />
    <None Remove="Backup Code\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\prdrecordsheet - bak.js" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\SGAController-bak.txt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\PrintPR\" />
    <Folder Include="wwwroot\UploadedFiles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.7.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\PPStock\AttendanceUplfile.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\PPStock\OrderDetail.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\PPStock\UserStockTools.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\orderdetail.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
